/// <auto-generated>
/// This code was auto-generated by Lackluster command line utils on 5/2/2017 21:23:43 UTC. Do not manually edit this file.
/// </auto-generated>
using Lackluster.Elements;

namespace Lackluster.Infrastructure
{
	public abstract partial class Component : BaseObject
	{	
		protected virtual Anchor A(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Anchor(children);
		}
	
		protected virtual Anchor A(System.String href, System.String text)
		{
			return new Anchor(href, text);
		}
	
		protected virtual Article Article(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Article(children);
		}
	
		protected virtual Blockquote Blockquote(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Blockquote(children);
		}
	
		protected virtual Blockquote Blockquote(System.String text)
		{
			return new Blockquote(text);
		}
	
		protected virtual Body Body(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Body(children);
		}
	
		protected virtual Code Code(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Code(children);
		}
	
		protected virtual Code Code(System.String text)
		{
			return new Code(text);
		}
	
		protected virtual Div Div(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Div(children);
		}
	
		protected virtual Head Head(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Head(children);
		}
	
		protected virtual H1 H1(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H1(children);
		}
	
		protected virtual H1 H1(System.String text)
		{
			return new H1(text);
		}
	
		protected virtual H2 H2(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H2(children);
		}
	
		protected virtual H2 H2(System.String text)
		{
			return new H2(text);
		}
	
		protected virtual H3 H3(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H3(children);
		}
	
		protected virtual H3 H3(System.String text)
		{
			return new H3(text);
		}
	
		protected virtual H4 H4(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H4(children);
		}
	
		protected virtual H4 H4(System.String text)
		{
			return new H4(text);
		}
	
		protected virtual H5 H5(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H5(children);
		}
	
		protected virtual H5 H5(System.String text)
		{
			return new H5(text);
		}
	
		protected virtual H6 H6(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new H6(children);
		}
	
		protected virtual H6 H6(System.String text)
		{
			return new H6(text);
		}
	
		protected virtual Html Html(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Html(children);
		}
	
		protected virtual Link Link(System.String relType, System.String href)
		{
			return new Link(relType, href);
		}
	
		protected virtual ListItem Li(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new ListItem(children);
		}
	
		protected virtual ListItem Li(System.String text)
		{
			return new ListItem(text);
		}
	
		protected virtual Meta Meta(System.String name, System.String content)
		{
			return new Meta(name, content);
		}
	
		protected virtual OrderedList Ol(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new OrderedList(children);
		}
	
		protected virtual OrderedList Ol(System.String text)
		{
			return new OrderedList(text);
		}
	
		protected virtual Paragraph P(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Paragraph(children);
		}
	
		protected virtual Paragraph P(System.String text)
		{
			return new Paragraph(text);
		}
	
		protected virtual Pre Pre(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Pre(children);
		}
	
		protected virtual Pre Pre(System.String text)
		{
			return new Pre(text);
		}
	
		protected virtual Section Section(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Section(children);
		}
	
		protected virtual Span Span(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new Span(children);
		}
	
		protected virtual Span Span(System.String text)
		{
			return new Span(text);
		}
	
		protected virtual Text Text(System.String text)
		{
			return new Text(text);
		}
	
		protected virtual UnorderedList Ul(params Lackluster.Infrastructure.BaseObject[] children)
		{
			return new UnorderedList(children);
		}
	}
}