/// <auto-generated>
/// This code was auto-generated by Lackluster command line utils on 5/2/2017 02:13:40 UTC. Do not manually edit this file.
/// </auto-generated>
using Lackluster.Elements;

namespace Lackluster.Infrastructure
{
	public abstract partial class Component : BaseObject
	{	
		protected virtual Anchor Anchor(params BaseObject[] children)
		{
			return new Anchor(null, null, null, children);
		}

		protected virtual Anchor Anchor(string text)
		{
			return new Anchor(null, null, null, new Text(text));
		}
	
		protected virtual Article Article(params BaseObject[] children)
		{
			return new Article(null, null, null, children);
		}
	
		protected virtual Blockquote Blockquote(params BaseObject[] children)
		{
			return new Blockquote(null, null, null, children);
		}

		protected virtual Blockquote Blockquote(string text)
		{
			return new Blockquote(null, null, null, new Text(text));
		}
	
		protected virtual Body Body(params BaseObject[] children)
		{
			return new Body(null, null, null, children);
		}
	
		protected virtual Code Code(params BaseObject[] children)
		{
			return new Code(null, null, null, children);
		}

		protected virtual Code Code(string text)
		{
			return new Code(null, null, null, new Text(text));
		}
	
		protected virtual Div Div(params BaseObject[] children)
		{
			return new Div(null, null, null, children);
		}
	
		protected virtual Head Head(params BaseObject[] children)
		{
			return new Head(null, null, null, children);
		}
	
		protected virtual H1 H1(params BaseObject[] children)
		{
			return new H1(null, null, null, children);
		}

		protected virtual H1 H1(string text)
		{
			return new H1(null, null, null, new Text(text));
		}
	
		protected virtual H2 H2(params BaseObject[] children)
		{
			return new H2(null, null, null, children);
		}

		protected virtual H2 H2(string text)
		{
			return new H2(null, null, null, new Text(text));
		}
	
		protected virtual H3 H3(params BaseObject[] children)
		{
			return new H3(null, null, null, children);
		}

		protected virtual H3 H3(string text)
		{
			return new H3(null, null, null, new Text(text));
		}
	
		protected virtual H4 H4(params BaseObject[] children)
		{
			return new H4(null, null, null, children);
		}

		protected virtual H4 H4(string text)
		{
			return new H4(null, null, null, new Text(text));
		}
	
		protected virtual H5 H5(params BaseObject[] children)
		{
			return new H5(null, null, null, children);
		}

		protected virtual H5 H5(string text)
		{
			return new H5(null, null, null, new Text(text));
		}
	
		protected virtual H6 H6(params BaseObject[] children)
		{
			return new H6(null, null, null, children);
		}

		protected virtual H6 H6(string text)
		{
			return new H6(null, null, null, new Text(text));
		}
	
		protected virtual Html Html(params BaseObject[] children)
		{
			return new Html(null, null, null, children);
		}
	
		protected virtual Link Link(params BaseObject[] children)
		{
			return new Link(null, null, null, children);
		}
	
		protected virtual ListItem ListItem(params BaseObject[] children)
		{
			return new ListItem(null, null, null, children);
		}

		protected virtual ListItem ListItem(string text)
		{
			return new ListItem(null, null, null, new Text(text));
		}
	
		protected virtual Meta Meta(params BaseObject[] children)
		{
			return new Meta(null, null, null, children);
		}
	
		protected virtual OrderedList OrderedList(params BaseObject[] children)
		{
			return new OrderedList(null, null, null, children);
		}
	
		protected virtual Paragraph Paragraph(params BaseObject[] children)
		{
			return new Paragraph(null, null, null, children);
		}

		protected virtual Paragraph Paragraph(string text)
		{
			return new Paragraph(null, null, null, new Text(text));
		}
	
		protected virtual Pre Pre(params BaseObject[] children)
		{
			return new Pre(null, null, null, children);
		}

		protected virtual Pre Pre(string text)
		{
			return new Pre(null, null, null, new Text(text));
		}
	
		protected virtual Section Section(params BaseObject[] children)
		{
			return new Section(null, null, null, children);
		}
	
		protected virtual Small Small(params BaseObject[] children)
		{
			return new Small(null, null, null, children);
		}

		protected virtual Small Small(string text)
		{
			return new Small(null, null, null, new Text(text));
		}
	
		protected virtual Span Span(params BaseObject[] children)
		{
			return new Span(null, null, null, children);
		}

		protected virtual Span Span(string text)
		{
			return new Span(null, null, null, new Text(text));
		}
	
		protected virtual Text Text(params BaseObject[] children)
		{
			return new Text(null, null, null, children);
		}

		protected virtual Text Text(string text)
		{
			return new Text(null, null, null, new Text(text));
		}
	
		protected virtual UnorderedList UnorderedList(params BaseObject[] children)
		{
			return new UnorderedList(null, null, null, children);
		}
	}
}